---
title: "202508Figure7"
author: "Jiantong Bao"
date: "2025-08-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Figure 5A
```{r}
Bcell <- readRDS("/home/data/path/to/directory/Bcell.annotated.rds")
suppressPackageStartupMessages({
  library(Seurat)
  library(ggplot2)
  library(dplyr)
})


genes <- c("NR4A1","NR4A2","NR4A3","CD83","ENTPD1","NT5E")


DefaultAssay(Bcell) <- "RNA"
expr <- FetchData(Bcell, vars = c(genes, "celltype"))


df <- expr %>%
  tidyr::pivot_longer(cols = all_of(genes), names_to = "gene", values_to = "expression")

order_ct <- c("MZB-1","MZB-2","GCB","PB","Plasmablast","DN","Naive","TS",
              "AcB1","AcB2","AcB3","IgM-only","Memory")
df$celltype <- factor(df$celltype, levels = order_ct)
df$gene     <- factor(df$gene, levels = genes)

p <- ggplot(df, aes(x = celltype, y = expression, fill = celltype)) +
  geom_violin(scale = "width", trim = TRUE, color = "black") +
  facet_grid(rows = vars(gene), scales = "free_y", switch = "y") +
  theme_bw() +
  theme(
    strip.text.y = element_text(angle = 0, hjust = 1, size = 10),
    axis.text.x  = element_text(angle = 45, hjust = 1, size = 8),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_blank(),
    legend.position = "none"
  ) +
  ylab("Expression Level") +
  xlab("")

print(p)
```

# Figure 7B,C
```{r}
load("~/Project/5Dataset/13-CIBERSORTx/TCGA_survival.RData")
library(survival)
library(survminer)
library(dplyr)

exprSet <- tumor_samples
meta$GCB  <- exprSet[,"GCB"]
meta$MZB1 <- exprSet[,"MZB.1"]
meta$MZB2 <- exprSet[,"MZB.2"]


meta <- meta %>%
  mutate(
    time  = as.numeric(time),
    event = as.numeric(event)
  ) %>%
  tidyr::drop_na(time, event, GCB, MZB1, MZB2)


res.cut <- surv_cutpoint(
  meta,
  time = "time",
  event = "event",
  variables = c("GCB","MZB1","MZB2"),
  minprop = 0
)

summary(res.cut)

```

```{r}

### MZB1 
res.cat <- surv_categorize(res.cut)
sfit <- survfit(Surv(time, event)~MZB1, data=res.cat)
ggsurvplot(sfit, conf.int=F, pval=TRUE)

ggsurv_plot <- ggsurvplot(sfit,palette = c("#E7B800", "#2E9FDF"),
                          risk.table =TRUE,pval =TRUE,
                          conf.int =TRUE,xlab ="Time in months", 
                          ggtheme =theme_light(), 
                          ncensor.plot = TRUE)

print(ggsurv_plot)


### MZB2 
sfit <- survfit(Surv(time, event)~MZB2, data=res.cat)
ggsurvplot(sfit, conf.int=F, pval=TRUE)

ggsurv_plot <-ggsurvplot(sfit,palette = c("#E7B800", "#2E9FDF"),
                         risk.table =TRUE,pval =TRUE,
                         conf.int =TRUE,xlab ="Time in months", 
                         ggtheme =theme_light(), 
                         ncensor.plot = TRUE)

print(ggsurv_plot)
```
